### ISSUE TITLE
scrollDirection: Axis.vertical?,

### ISSUE THREAD

**Issue by klaszlo8207** [jakebonk/FlutterBoardView#3] opened 2020-05-08 17:25 UTC
How can I create a list board that is working up/down? not left/right

thanks

**Comment by Dhananjayan-PN** [comment] 2020-06-29 12:10
Hi,
I also would like to have it vertical. Can you please let me know how to do it?

**Comment by jakebonk** [comment] 2020-06-29 16:48
Duplicate of #5

**Closed by jakebonk** 2020-06-29 16:48 UTC
